### ISSUE TITLE
Add the ability to recolor the flat emoji

### ISSUE THREAD

**Issue by ryanlua** [michalleptuch/fluent-emoji-gallery#3]
Flat emojis can be recolored as seen when changing themes, why not add this functionality to be able to recolor flat emojis for the user to choose too? It would be nice to be able to preview the flat emojis in different colors without having to export to an external image editor.

![image](https://user-images.githubusercontent.com/80087248/234701121-59cc9641-db3b-43ae-a4e3-09ac43127fee.png) ![image](https://user-images.githubusercontent.com/80087248/234701179-9bb4988b-5767-49ca-96b9-1af63b422893.png)

WinUI 3 already has a built-in [colorpicker](winui3gallery://item/ColorPicker) and the icons already update color for theme so most of the coding for such is already done.

![image](https://user-images.githubusercontent.com/80087248/234702202-569e4dfa-b1af-45f8-b1bc-507b52d34620.png)

**Comment by michalleptuch** [comment]
Testing...
<img width="311" alt="image" src="https://user-images.githubusercontent.com/43097852/235508502-ef3b3705-8569-4c66-af8f-c49b523204e7.png">
