### ISSUE TITLE
Possibility for open source?

### ISSUE THREAD

**Issue by stamminator** [michalleptuch/fluent-emoji-gallery#8]
This app is exemplary. I'm currently learning WinUI 3, and I find that examining and tinkering with well-built apps is a great way to learn. For your paid apps, which are also very good, it makes total sense to keep the source private. But for this app, would you consider going open source?

**Comment by MattBDev** [comment]
I 100% agree. Going open source on this app would be very beneficial as an example for developers new to making great Windows.

**Comment by michalleptuch** [comment]
@stamminator @MattBDev I don't plan to share the source code of Fluent Emoji Gallery because it contains parts of the code that are also used in my other paid applications. Is there any particular feature or functionality that interests you the most?

**Comment by stamminator** [comment]
@michalleptuch While I'd like to see the architecture of the app as a whole for learning purposes, I also am specifically interested in how you generate image files from font glyphs. I'm trying to make a tool that takes in an emoji glyph character as a string specified by the user and returns a PNG, but my initial attempt using System.Drawing.Graphics to draw a bitmap looks bad and is only monochrome. I figure there's got to be a way to grab a glyph as an SVG, then convert to PNG, but I haven't figured it out yet.

**Comment by michalleptuch** [comment]
I don't use glyphs to generate images. Microsoft shares two repositories of emojis (static and animated), and I use them in my app. Repos:
- https://github.com/microsoft/fluentui-emoji
- https://github.com/microsoft/fluentui-emoji-animated
